# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class GitPromptString < Formula
  desc "A shell agnostic git prompt written in Go"
  homepage "https://github.com/mikesmithgh/git-prompt-string"
  version "1.2.0"
  license "Apache-2.0"

  depends_on "git"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/mikesmithgh/git-prompt-string/releases/download/v1.2.0/git-prompt-string_Darwin_x86_64.tar.gz"
      sha256 "fbb81cae9aa8ba84a7a238d3d4f0235854cef20df3b79b2c32b5ae59dc06d162"

      def install
        bin.install "git-prompt-string"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/mikesmithgh/git-prompt-string/releases/download/v1.2.0/git-prompt-string_Darwin_arm64.tar.gz"
      sha256 "fec41ea89ee95a26a6ce3eed7ca215ea4fb117edab85880b41f4502824682655"

      def install
        bin.install "git-prompt-string"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/mikesmithgh/git-prompt-string/releases/download/v1.2.0/git-prompt-string_Linux_arm64.tar.gz"
      sha256 "51ff101c9f652b59743597c4a74c2048aca938df57e6d9b913650d76b6015c13"

      def install
        bin.install "git-prompt-string"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/mikesmithgh/git-prompt-string/releases/download/v1.2.0/git-prompt-string_Linux_x86_64.tar.gz"
      sha256 "53151d6beac67d627cc39126e6ae8916a8222aa96acc7d39e644ef182ce2c2c1"

      def install
        bin.install "git-prompt-string"
      end
    end
  end

  test do
    system "#{bin}/git-prompt-string --version"
  end
end
