# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class GitPromptString < Formula
  desc "A shell agnostic git prompt written in Go"
  homepage "https://github.com/mikesmithgh/git-prompt-string"
  version "1.2.1"
  license "Apache-2.0"

  depends_on "git"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/mikesmithgh/git-prompt-string/releases/download/v1.2.1/git-prompt-string_Darwin_x86_64.tar.gz"
      sha256 "f4d2154c4d31fd7729c6e5ae417ed822b24f1283c985a260520a2c8510f11bbb"

      def install
        bin.install "git-prompt-string"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/mikesmithgh/git-prompt-string/releases/download/v1.2.1/git-prompt-string_Darwin_arm64.tar.gz"
      sha256 "1ef827b7eaa18878c0274e6b5eee37df9dcaeb368a478aec9fde8564aa74794e"

      def install
        bin.install "git-prompt-string"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/mikesmithgh/git-prompt-string/releases/download/v1.2.1/git-prompt-string_Linux_x86_64.tar.gz"
      sha256 "4d426522c32d86272f000300df356ca6c50f36ccb76924786a95bbdc20f1aaa0"

      def install
        bin.install "git-prompt-string"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/mikesmithgh/git-prompt-string/releases/download/v1.2.1/git-prompt-string_Linux_arm64.tar.gz"
      sha256 "ed73c868f56aed6c9585a06cb31f9b864d8c8605b1cfbf78fb997b0a1a8018de"

      def install
        bin.install "git-prompt-string"
      end
    end
  end

  test do
    system "#{bin}/git-prompt-string --version"
  end
end
